### ISSUE TITLE
Backup script broken for GitLab V4 API

### ISSUE THREAD

**Issue by borupdaniel** [nckz/BackupHub#1]
This script no longer works. The issue appears to be Gitlab removing support for their V3 API since July 2018.

Running the script with python-gitlab 0.13 produces the following error:
```bash
gitlab.exceptions.GitlabListError: 410: b'{"error":"API V3 is no longer supported. Use API V4 instead."}'
```

Upgrading python-gitlab to the latest (1.8.0) hangs during execution. From a partial traceback (after ctrl-c) the first issue seems to be with getting the list of projects:
```bash
Traceback (most recent call last):
  File "./BackupHub.py", line 224, in <module>
    webapi = GitLabAPI(options.token, options.website)
  File "./BackupHub.py", line 55, in __init__
    self._projects = self._gl.projects.list(all=True)
```

**Comment by borupdaniel** [comment]
This issue appears to be resolved by pull request #2
